# Site settings
title: Ethan Perez
email: ethan@ethanperez.com
url: "http://ethanperez.com"
permalink: /posts/:title
twitter_username: ethanperez44
github_username: ethanperez

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from